using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


#region Class_Company_code_datanamespace SectionConfiguration{	public class Company_code_data	{		public object GetClass(string str)		{			object Obj;			switch (str)			{				case "CAL001CEXT":					Obj = new SectionConfiguration.CAL001CEXT.Company_code_data();					return Obj;				case "CAL001CMC":					Obj = new SectionConfiguration.CAL001CMC.Company_code_data();					return Obj;				case "CAL001Z001":					Obj = new SectionConfiguration.CAL001Z001.Company_code_data();					return Obj;				case "CAL001Z002":					Obj = new SectionConfiguration.CAL001Z002.Company_code_data();					return Obj;				case "CAL001Z003":					Obj = new SectionConfiguration.CAL001Z003.Company_code_data();					return Obj;				case "CAL001Z004":					Obj = new SectionConfiguration.CAL001Z004.Company_code_data();					return Obj;				case "CAL001Z005":					Obj = new SectionConfiguration.CAL001Z005.Company_code_data();					return Obj;				case "CAL001Z006":					Obj = new SectionConfiguration.CAL001Z006.Company_code_data();					return Obj;				case "CAL001Z008":					Obj = new SectionConfiguration.CAL001Z008.Company_code_data();					return Obj;				case "CCL001CEXT":					Obj = new SectionConfiguration.CCL001CEXT.Company_code_data();					return Obj;				case "CCL001CMC":					Obj = new SectionConfiguration.CCL001CMC.Company_code_data();					return Obj;				case "CCL001Z001":					Obj = new SectionConfiguration.CCL001Z001.Company_code_data();					return Obj;				case "CCL001Z002":					Obj = new SectionConfiguration.CCL001Z002.Company_code_data();					return Obj;				case "CCL001Z003":					Obj = new SectionConfiguration.CCL001Z003.Company_code_data();					return Obj;				case "CCL001Z004":					Obj = new SectionConfiguration.CCL001Z004.Company_code_data();					return Obj;				case "CCL001Z005":					Obj = new SectionConfiguration.CCL001Z005.Company_code_data();					return Obj;				case "CCL001Z006":					Obj = new SectionConfiguration.CCL001Z006.Company_code_data();					return Obj;				case "CCL001Z008":					Obj = new SectionConfiguration.CCL001Z008.Company_code_data();					return Obj;				//Start Change by Swati
                case "CAL001Z055":
                    Obj = new SectionConfiguration.CAL001Z055.Company_code_data();
                    return Obj;
				//End Change
                default:					return null;			}		}	}}#endregion
#region Class_Company_code_data_CAL001CEXTnamespace SectionConfiguration.CAL001CEXT{	public class Company_code_data	{		#region Properties		public static int chkIndicaterRecordPayHis		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int ddlPlanningGroup		{ 			get { return 3; }		}		public static int ddlReconAcc		{ 			get { return 3; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int ddlTermsPaymentKey		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtAuthorizationGroup		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CAL001CMCnamespace SectionConfiguration.CAL001CMC{	public class Company_code_data	{		#region Properties		public static int ddlReconAcc		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int ddlPlanningGroup		{ 			get { return 2; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CAL001Z001namespace SectionConfiguration.CAL001Z001{	public class Company_code_data	{		#region Properties		public static int ddlPlanningGroup		{ 			get { return 1; }		}		public static int ddlReconAcc		{ 			get { return 1; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CAL001Z002namespace SectionConfiguration.CAL001Z002{	public class Company_code_data	{		#region Properties		public static int ddlReconAcc		{ 			get { return 1; }		}		public static int ddlPlanningGroup		{ 			get { return 1; }		}		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CAL001Z003namespace SectionConfiguration.CAL001Z003{	public class Company_code_data	{		#region Properties		public static int ddlPlanningGroup		{ 			get { return 1; }		}		public static int ddlReconAcc		{ 			get { return 1; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CAL001Z004namespace SectionConfiguration.CAL001Z004{	public class Company_code_data	{		#region Properties		public static int ddlPlanningGroup		{ 			get { return 1; }		}		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int ddlReconAcc		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CAL001Z005namespace SectionConfiguration.CAL001Z005{	public class Company_code_data	{		#region Properties		public static int ddlPlanningGroup		{ 			get { return 1; }		}		public static int ddlReconAcc		{ 			get { return 1; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CAL001Z006namespace SectionConfiguration.CAL001Z006{	public class Company_code_data	{		#region Properties		public static int ddlPlanningGroup		{ 			get { return 1; }		}		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int ddlReconAcc		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CAL001Z008namespace SectionConfiguration.CAL001Z008{	public class Company_code_data	{		#region Properties		public static int ddlPlanningGroup		{ 			get { return 1; }		}		public static int ddlReconAcc		{ 			get { return 1; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CCL001CEXTnamespace SectionConfiguration.CCL001CEXT{	public class Company_code_data	{		#region Properties		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkIndicaterRecordPayHis		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int ddlPlanningGroup		{ 			get { return 3; }		}		public static int ddlReconAcc		{ 			get { return 3; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int ddlTermsPaymentKey		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtAuthorizationGroup		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CCL001CMCnamespace SectionConfiguration.CCL001CMC{	public class Company_code_data	{		#region Properties		public static int ddlPlanningGroup		{ 			get { return 2; }		}		public static int ddlReconAcc		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CCL001Z001namespace SectionConfiguration.CCL001Z001{	public class Company_code_data	{		#region Properties		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int ddlReconAcc		{ 			get { return 2; }		}		public static int ddlPlanningGroup		{ 			get { return 2; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CCL001Z002namespace SectionConfiguration.CCL001Z002{	public class Company_code_data	{		#region Properties		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int ddlPlanningGroup		{ 			get { return 2; }		}		public static int ddlReconAcc		{ 			get { return 2; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CCL001Z003namespace SectionConfiguration.CCL001Z003{	public class Company_code_data	{		#region Properties		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int ddlReconAcc		{ 			get { return 2; }		}		public static int ddlPlanningGroup		{ 			get { return 2; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CCL001Z004namespace SectionConfiguration.CCL001Z004{	public class Company_code_data	{		#region Properties		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int ddlPlanningGroup		{ 			get { return 2; }		}		public static int ddlReconAcc		{ 			get { return 2; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CCL001Z005namespace SectionConfiguration.CCL001Z005{	public class Company_code_data	{		#region Properties		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int ddlReconAcc		{ 			get { return 2; }		}		public static int ddlPlanningGroup		{ 			get { return 2; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CCL001Z006namespace SectionConfiguration.CCL001Z006{	public class Company_code_data	{		#region Properties		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int ddlPlanningGroup		{ 			get { return 2; }		}		public static int ddlReconAcc		{ 			get { return 2; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Company_code_data_CCL001Z008namespace SectionConfiguration.CCL001Z008{	public class Company_code_data	{		#region Properties		public static int chkIndicaterRecordPayHis		{ 			get { return 2; }		}		public static int txtAuthorizationGroup		{ 			get { return 2; }		}		public static int ddlTermsPaymentKey		{ 			get { return 2; }		}		public static int ddlReconAcc		{ 			get { return 2; }		}		public static int ddlPlanningGroup		{ 			get { return 2; }		}		public static int ddlShortKeyBank		{ 			get { return 3; }		}		public static int txtBlockKeyPayment		{ 			get { return 3; }		}		public static int txtAccountionClerk		{ 			get { return 3; }		}		public static int txtAccNumberALterPlayer		{ 			get { return 3; }		}		public static int chkIndicatorPayAll		{ 			get { return 3; }		}		public static int chkindicatorPeriodicAccount		{ 			get { return 3; }		}		public static int txtIndiPaymentNotice		{ 			get { return 3; }		}		public static int txtKeyPaymentGrouping		{ 			get { return 3; }		}		public static int txtIndipaymentWoCleared		{ 			get { return 3; }		}		public static int txtNextPaye		{ 			get { return 3; }		}		public static int txtMemo		{ 			get { return 3; }		}		public static int txtListPaymentConsidered		{ 			get { return 3; }		}		public static int txtkeySortingAssignment		{ 			get { return 3; }		}		public static int txtDeletionFlagMasterRecord		{ 			get { return 3; }		}		public static int txtIndiClearingBetwCust		{ 			get { return 3; }		}		public static int txtHeadOfficeAccNumber		{ 			get { return 3; }		}		public static int txtIndiPaymentlegalDepartment		{ 			get { return 3; }		}		public static int txtIndiPaymentAccountingDepart		{ 			get { return 3; }		}		public static int txtIndiPayment		{ 			get { return 3; }		}		public static int txtIndiForWithHoldingTaxType		{ 			get { return 3; }		}		public static int txtPostingBlockCompanyCode		{ 			get { return 3; }		}		public static int txtPaymentTermCreditMemos		{ 			get { return 3; }		}		public static int txtOurAccoCust		{ 			get { return 3; }		}		public static int txtWithholdingTaxCountry		{ 			get { return 3; }		}		public static int txtWithholdingTaxCode		{ 			get { return 3; }		}		public static int txtToleranceGroupBussAcc		{ 			get { return 3; }		}		public static int txtPreviousRecordNumber		{ 			get { return 3; }		}		public static int txtWitHoldingTaxIdenNumb		{ 			get { return 3; }		}		#endregion	}}#endregion
//Start Change by Swati
#region Class_Company_code_data_CAL001Z055
namespace SectionConfiguration.CAL001Z055
{
    public class Company_code_data
    {


        #region Properties
        public static int chkIndicaterRecordPayHis
        {
            get { return 2; }
        }

        public static int txtAuthorizationGroup
        {
            get { return 2; }
        }

        public static int ddlTermsPaymentKey
        {
            get { return 2; }
        }

        public static int ddlReconAcc
        {
            get { return 2; }
        }

        public static int ddlPlanningGroup
        {
            get { return 2; }
        }

        public static int ddlShortKeyBank
        {
            get { return 3; }
        }

        public static int txtBlockKeyPayment
        {
            get { return 3; }
        }

        public static int txtAccountionClerk
        {
            get { return 3; }
        }

        public static int txtAccNumberALterPlayer
        {
            get { return 3; }
        }

        public static int chkIndicatorPayAll
        {
            get { return 3; }
        }

        public static int chkindicatorPeriodicAccount
        {
            get { return 3; }
        }

        public static int txtIndiPaymentNotice
        {
            get { return 3; }
        }

        public static int txtKeyPaymentGrouping
        {
            get { return 3; }
        }

        public static int txtIndipaymentWoCleared
        {
            get { return 3; }
        }

        public static int txtNextPaye
        {
            get { return 3; }
        }

        public static int txtMemo
        {
            get { return 3; }
        }

        public static int txtListPaymentConsidered
        {
            get { return 3; }
        }

        public static int txtkeySortingAssignment
        {
            get { return 3; }
        }

        public static int txtDeletionFlagMasterRecord
        {
            get { return 3; }
        }

        public static int txtIndiClearingBetwCust
        {
            get { return 3; }
        }

        public static int txtHeadOfficeAccNumber
        {
            get { return 3; }
        }

        public static int txtIndiPaymentlegalDepartment
        {
            get { return 3; }
        }

        public static int txtIndiPaymentAccountingDepart
        {
            get { return 3; }
        }

        public static int txtIndiPayment
        {
            get { return 3; }
        }

        public static int txtIndiForWithHoldingTaxType
        {
            get { return 3; }
        }

        public static int txtPostingBlockCompanyCode
        {
            get { return 3; }
        }

        public static int txtPaymentTermCreditMemos
        {
            get { return 3; }
        }

        public static int txtOurAccoCust
        {
            get { return 3; }
        }

        public static int txtWithholdingTaxCountry
        {
            get { return 3; }
        }

        public static int txtWithholdingTaxCode
        {
            get { return 3; }
        }

        public static int txtToleranceGroupBussAcc
        {
            get { return 3; }
        }

        public static int txtPreviousRecordNumber
        {
            get { return 3; }
        }

        public static int txtWitHoldingTaxIdenNumb
        {
            get { return 3; }
        }




        #endregion
    }

}

#endregion
//End Change