using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


#region Class_Sales_area_datanamespace SectionConfiguration{	public class Sales_area_data	{		public object GetClass(string str)		{			object Obj;			switch (str)			{				case "CAL001CEXT":					Obj = new SectionConfiguration.CAL001CEXT.Sales_area_data();					return Obj;				case "CAL001CMC":					Obj = new SectionConfiguration.CAL001CMC.Sales_area_data();					return Obj;				case "CAL001Z001":					Obj = new SectionConfiguration.CAL001Z001.Sales_area_data();					return Obj;				case "CAL001Z002":					Obj = new SectionConfiguration.CAL001Z002.Sales_area_data();					return Obj;				case "CAL001Z003":					Obj = new SectionConfiguration.CAL001Z003.Sales_area_data();					return Obj;				case "CAL001Z004":					Obj = new SectionConfiguration.CAL001Z004.Sales_area_data();					return Obj;				case "CAL001Z005":					Obj = new SectionConfiguration.CAL001Z005.Sales_area_data();					return Obj;				case "CAL001Z006":					Obj = new SectionConfiguration.CAL001Z006.Sales_area_data();					return Obj;				case "CAL001Z008":					Obj = new SectionConfiguration.CAL001Z008.Sales_area_data();					return Obj;				case "CCL001CEXT":					Obj = new SectionConfiguration.CCL001CEXT.Sales_area_data();					return Obj;				case "CCL001CMC":					Obj = new SectionConfiguration.CCL001CMC.Sales_area_data();					return Obj;				case "CCL001Z001":					Obj = new SectionConfiguration.CCL001Z001.Sales_area_data();					return Obj;				case "CCL001Z002":					Obj = new SectionConfiguration.CCL001Z002.Sales_area_data();					return Obj;				case "CCL001Z003":					Obj = new SectionConfiguration.CCL001Z003.Sales_area_data();					return Obj;				case "CCL001Z004":					Obj = new SectionConfiguration.CCL001Z004.Sales_area_data();					return Obj;				case "CCL001Z005":					Obj = new SectionConfiguration.CCL001Z005.Sales_area_data();					return Obj;				case "CCL001Z006":					Obj = new SectionConfiguration.CCL001Z006.Sales_area_data();					return Obj;				case "CCL001Z008":					Obj = new SectionConfiguration.CCL001Z008.Sales_area_data();					return Obj;				//Start Change by Swati
                case "CAL001Z055":
                    Obj = new SectionConfiguration.CAL001Z055.Sales_area_data();
                    return Obj;
				//End Change
                default:					return null;			}		}	}}#endregion
#region Class_Sales_area_data_CAL001CEXTnamespace SectionConfiguration.CAL001CEXT{	public class Sales_area_data	{		#region Properties		public static int ddlCreditControlArea		{ 			get { return 3; }		}		public static int ddlCreditCurrency		{ 			get { return 3; }		}		public static int ddlCurrency		{ 			get { return 3; }		}		public static int ddlDeliveringPlant		{ 			get { return 3; }		}		public static int ddlInvoiceDates		{ 			get { return 3; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 3; }		}		public static int ddlPriceGroup		{ 			get { return 3; }		}		public static int ddlRiskcategory		{ 			get { return 3; }		}		public static int ddlSalesDistrict		{ 			get { return 3; }		}		public static int ddlSalesGroup		{ 			get { return 3; }		}		public static int ddlSalesOffice		{ 			get { return 3; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		public static int txtCustomer_credit_limit		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CAL001CMCnamespace SectionConfiguration.CAL001CMC{	public class Sales_area_data	{		#region Properties		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int ddlCreditControlArea		{ 			get { return 2; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlCurrency		{ 			get { return 2; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CAL001Z001namespace SectionConfiguration.CAL001Z001{	public class Sales_area_data	{		#region Properties		public static int ddlSalesOffice		{ 			get { return 1; }		}		public static int ddlSalesGroup		{ 			get { return 1; }		}		public static int ddlSalesDistrict		{ 			get { return 1; }		}		public static int ddlCreditControlArea		{ 			get { return 1; }		}		public static int ddlDeliveringPlant		{ 			get { return 1; }		}		public static int ddlCurrency		{ 			get { return 1; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CAL001Z002namespace SectionConfiguration.CAL001Z002{	public class Sales_area_data	{		#region Properties		public static int ddlCurrency		{ 			get { return 1; }		}		public static int ddlDeliveringPlant		{ 			get { return 1; }		}		public static int ddlCreditControlArea		{ 			get { return 1; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CAL001Z003namespace SectionConfiguration.CAL001Z003{	public class Sales_area_data	{		#region Properties		public static int ddlSalesOffice		{ 			get { return 1; }		}		public static int ddlSalesGroup		{ 			get { return 1; }		}		public static int ddlSalesDistrict		{ 			get { return 1; }		}		public static int ddlCurrency		{ 			get { return 1; }		}		public static int ddlDeliveringPlant		{ 			get { return 1; }		}		public static int ddlCreditControlArea		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 2; }		}		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int ddlCreditCurrency		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CAL001Z004namespace SectionConfiguration.CAL001Z004{	public class Sales_area_data	{		#region Properties		public static int ddlDeliveringPlant		{ 			get { return 1; }		}		public static int ddlCreditControlArea		{ 			get { return 2; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlCurrency		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CAL001Z005namespace SectionConfiguration.CAL001Z005{	public class Sales_area_data	{		#region Properties		public static int ddlCurrency		{ 			get { return 1; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		public static int txtCustomer_credit_limit		{ 			get { return 3; }		}		public static int ddlRiskcategory		{ 			get { return 3; }		}		public static int ddlCreditControlArea		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CAL001Z006namespace SectionConfiguration.CAL001Z006{	public class Sales_area_data	{		#region Properties		public static int ddlCreditControlArea		{ 			get { return 1; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlCurrency		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		public static int ddlSalesOffice		{ 			get { return 3; }		}		public static int ddlSalesDistrict		{ 			get { return 3; }		}		public static int ddlSalesGroup		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CAL001Z008namespace SectionConfiguration.CAL001Z008{	public class Sales_area_data	{		#region Properties		public static int ddlCurrency		{ 			get { return 1; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 3; }		}		public static int ddlInvoiceDates		{ 			get { return 3; }		}		public static int ddlCreditControlArea		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CCL001CEXTnamespace SectionConfiguration.CCL001CEXT{	public class Sales_area_data	{		#region Properties		public static int ddlCreditControlArea		{ 			get { return 3; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 3; }		}		public static int ddlPriceGroup		{ 			get { return 3; }		}		public static int ddlRiskcategory		{ 			get { return 3; }		}		public static int ddlCreditCurrency		{ 			get { return 3; }		}		public static int ddlCurrency		{ 			get { return 3; }		}		public static int ddlDeliveringPlant		{ 			get { return 3; }		}		public static int ddlInvoiceDates		{ 			get { return 3; }		}		public static int ddlSalesDistrict		{ 			get { return 3; }		}		public static int ddlSalesGroup		{ 			get { return 3; }		}		public static int ddlSalesOffice		{ 			get { return 3; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		public static int txtCustomer_credit_limit		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CCL001CMCnamespace SectionConfiguration.CCL001CMC{	public class Sales_area_data	{		#region Properties		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int ddlCreditControlArea		{ 			get { return 2; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlCurrency		{ 			get { return 2; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CCL001Z001namespace SectionConfiguration.CCL001Z001{	public class Sales_area_data	{		#region Properties		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int ddlCurrency		{ 			get { return 2; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlCreditControlArea		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CCL001Z002namespace SectionConfiguration.CCL001Z002{	public class Sales_area_data	{		#region Properties		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int ddlCurrency		{ 			get { return 2; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlCreditControlArea		{ 			get { return 2; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CCL001Z003namespace SectionConfiguration.CCL001Z003{	public class Sales_area_data	{		#region Properties		public static int txtcountryKeyExport		{ 			get { return 2; }		}		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int ddlCurrency		{ 			get { return 2; }		}		public static int ddlCreditControlArea		{ 			get { return 2; }		}		public static int ddlCreditCurrency		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CCL001Z004namespace SectionConfiguration.CCL001Z004{	public class Sales_area_data	{		#region Properties		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlCreditControlArea		{ 			get { return 2; }		}		public static int ddlCurrency		{ 			get { return 2; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CCL001Z005namespace SectionConfiguration.CCL001Z005{	public class Sales_area_data	{		#region Properties		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int ddlCurrency		{ 			get { return 2; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlCreditControlArea		{ 			get { return 3; }		}		public static int ddlRiskcategory		{ 			get { return 3; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		public static int txtCustomer_credit_limit		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CCL001Z006namespace SectionConfiguration.CCL001Z006{	public class Sales_area_data	{		#region Properties		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlCurrency		{ 			get { return 2; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int ddlInvoiceDates		{ 			get { return 2; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 2; }		}		public static int ddlCreditControlArea		{ 			get { return 2; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 3; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		public static int ddlSalesGroup		{ 			get { return 3; }		}		public static int ddlSalesOffice		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Sales_area_data_CCL001Z008namespace SectionConfiguration.CCL001Z008{	public class Sales_area_data	{		#region Properties		public static int ddlSalesOffice		{ 			get { return 2; }		}		public static int ddlSalesGroup		{ 			get { return 2; }		}		public static int txtCustomer_credit_limit		{ 			get { return 2; }		}		public static int ddlSalesDistrict		{ 			get { return 2; }		}		public static int ddlRiskcategory		{ 			get { return 2; }		}		public static int ddlPriceGroup		{ 			get { return 2; }		}		public static int ddlDeliveringPlant		{ 			get { return 2; }		}		public static int ddlCurrency		{ 			get { return 2; }		}		public static int ddlCreditCurrency		{ 			get { return 2; }		}		public static int ddlCreditControlArea		{ 			get { return 3; }		}		public static int ddlInvoiceListSchedule		{ 			get { return 3; }		}		public static int ddlInvoiceDates		{ 			get { return 3; }		}		public static int txtcountryKeyExport		{ 			get { return 3; }		}		#endregion	}}#endregion 
//Start Change by Swati
#region Class_Sales_area_data_CAL001Z055

namespace SectionConfiguration.CAL001Z055
{
    public class Sales_area_data
    {
        #region Properties

        public static int ddlSalesOffice
        {
            get { return 2; }
        }

        public static int ddlSalesGroup
        {
            get { return 2; }
        }

        public static int txtCustomer_credit_limit
        {
            get { return 2; }
        }

        public static int ddlSalesDistrict
        {
            get { return 2; }
        }

        public static int ddlRiskcategory
        {
            get { return 2; }
        }

        public static int ddlPriceGroup
        {
            get { return 2; }
        }

        public static int ddlDeliveringPlant
        {
            get { return 2; }
        }

        public static int ddlCurrency
        {
            get { return 2; }
        }

        public static int ddlCreditCurrency
        {
            get { return 2; }
        }

        public static int ddlCreditControlArea
        {
            get { return 2; }
        }

        public static int ddlInvoiceListSchedule
        {
            get { return 3; }
        }

        public static int ddlInvoiceDates
        {
            get { return 3; }
        }

        public static int txtcountryKeyExport
        {
            get { return 3; }
        }


        #endregion
    }

}

#endregion
//End Change