using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


#region Class_Vendor_Master_Block_or_Unblocknamespace SectionConfiguration{	public class Vendor_Master_Block_or_Unblock	{		public object GetClass(string str)		{			object Obj;			switch (str)			{				case "UAL001VMB":					Obj = new SectionConfiguration.UAL001VMB.Vendor_Master_Block_or_Unblock();					return Obj;				case "UAL001VMU":					Obj = new SectionConfiguration.UAL001VMU.Vendor_Master_Block_or_Unblock();					return Obj;				case "UCL001VMB":					Obj = new SectionConfiguration.UCL001VMB.Vendor_Master_Block_or_Unblock();					return Obj;				case "UCL001VMU":					Obj = new SectionConfiguration.UCL001VMU.Vendor_Master_Block_or_Unblock();					return Obj;				default:					return null;			}		}	}}#endregion
#region Class_Vendor_Master_Block_or_Unblock_UAL001VMBnamespace SectionConfiguration.UAL001VMB{	public class Vendor_Master_Block_or_Unblock	{		#region Properties		public static int chkAllCompanies		{ 			get { return 2; }		}		public static int chkAllPurchasingOrg		{ 			get { return 2; }		}		public static int chkSelectedCompany		{ 			get { return 2; }		}		public static int chkSelectedPurchasingOrg		{ 			get { return 2; }		}		public static int ddlBlockFunction		{ 			get { return 2; }		}		public static int ddlPaymentBlock		{ 			get { return 2; }		}		public static int ddlPurchaseOrg		{ 			get { return 2; }		}		public static int txtRemarks		{ 			get { return 2; }		}		public static int ddlCompanyCode		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Vendor_Master_Block_or_Unblock_UAL001VMUnamespace SectionConfiguration.UAL001VMU{	public class Vendor_Master_Block_or_Unblock	{		#region Properties		public static int ddlBlockFunction		{ 			get { return 2; }		}		public static int ddlPurchaseOrg		{ 			get { return 2; }		}		public static int ddlPaymentBlock		{ 			get { return 2; }		}		public static int chkSelectedPurchasingOrg		{ 			get { return 2; }		}		public static int chkSelectedCompany		{ 			get { return 2; }		}		public static int chkAllPurchasingOrg		{ 			get { return 2; }		}		public static int chkAllCompanies		{ 			get { return 2; }		}		public static int txtRemarks		{ 			get { return 2; }		}		public static int ddlCompanyCode		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Vendor_Master_Block_or_Unblock_UCL001VMBnamespace SectionConfiguration.UCL001VMB{	public class Vendor_Master_Block_or_Unblock	{		#region Properties		public static int chkAllCompanies		{ 			get { return 2; }		}		public static int chkAllPurchasingOrg		{ 			get { return 2; }		}		public static int chkSelectedCompany		{ 			get { return 2; }		}		public static int chkSelectedPurchasingOrg		{ 			get { return 2; }		}		public static int ddlBlockFunction		{ 			get { return 2; }		}		public static int ddlPaymentBlock		{ 			get { return 2; }		}		public static int ddlPurchaseOrg		{ 			get { return 2; }		}		public static int txtRemarks		{ 			get { return 2; }		}		public static int ddlCompanyCode		{ 			get { return 3; }		}		#endregion	}}#endregion
#region Class_Vendor_Master_Block_or_Unblock_UCL001VMUnamespace SectionConfiguration.UCL001VMU{	public class Vendor_Master_Block_or_Unblock	{		#region Properties		public static int ddlPaymentBlock		{ 			get { return 2; }		}		public static int ddlBlockFunction		{ 			get { return 2; }		}		public static int chkSelectedPurchasingOrg		{ 			get { return 2; }		}		public static int chkSelectedCompany		{ 			get { return 2; }		}		public static int chkAllPurchasingOrg		{ 			get { return 2; }		}		public static int chkAllCompanies		{ 			get { return 2; }		}		public static int txtRemarks		{ 			get { return 2; }		}		public static int ddlPurchaseOrg		{ 			get { return 2; }		}		public static int ddlCompanyCode		{ 			get { return 3; }		}		#endregion	}}#endregion
