//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MW_TestEntities : DbContext
    {
        public MW_TestEntities()
            : base("name=MW_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_Section_Feild_Mapping> C_Section_Feild_Mapping { get; set; }
        public DbSet<FieldStatusMaster> FieldStatusMasters { get; set; }
        public DbSet<M_Module> M_Module { get; set; }
        public DbSet<SectionFieldMaster> SectionFieldMasters { get; set; }
        public DbSet<SectionMaster> SectionMasters { get; set; }
        public DbSet<M_Company> M_Company { get; set; }
        public DbSet<Dept_Module_Section_Mapping> Dept_Module_Section_Mapping { get; set; }
        public DbSet<Menu_Master> Menu_Master { get; set; }
        public DbSet<Profile_Master> Profile_Master { get; set; }
        public DbSet<Profile_Menu_Mapping> Profile_Menu_Mapping { get; set; }
        public DbSet<Profile_Module_Mapping> Profile_Module_Mapping { get; set; }
        public DbSet<M_Department> M_Department { get; set; }
        public DbSet<M_Plant_Group> M_Plant_Group { get; set; }
    
        public virtual ObjectResult<GenerateClassPropertyC_Result> GenerateClassPropertyC(Nullable<int> section_Id)
        {
            var section_IdParameter = section_Id.HasValue ?
                new ObjectParameter("Section_Id", section_Id) :
                new ObjectParameter("Section_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerateClassPropertyC_Result>("GenerateClassPropertyC", section_IdParameter);
        }
    
        public virtual ObjectResult<pr_GetCompanyList_Result> pr_GetCompanyList(Nullable<int> master_Header_Id, string section_Code, Nullable<int> reference_Id)
        {
            var master_Header_IdParameter = master_Header_Id.HasValue ?
                new ObjectParameter("Master_Header_Id", master_Header_Id) :
                new ObjectParameter("Master_Header_Id", typeof(int));
    
            var section_CodeParameter = section_Code != null ?
                new ObjectParameter("Section_Code", section_Code) :
                new ObjectParameter("Section_Code", typeof(string));
    
            var reference_IdParameter = reference_Id.HasValue ?
                new ObjectParameter("Reference_Id", reference_Id) :
                new ObjectParameter("Reference_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GetCompanyList_Result>("pr_GetCompanyList", master_Header_IdParameter, section_CodeParameter, reference_IdParameter);
        }
    }
}
