//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Section_Feild_Mapping
    {
        public decimal Section_Feild_Mapping_Id { get; set; }
        public Nullable<decimal> Module_Id { get; set; }
        public Nullable<decimal> Plant_Group_Id { get; set; }
        public Nullable<decimal> Section_Feild_Master_Id { get; set; }
        public Nullable<decimal> Feild_Status { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public string CreatedIp { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public string ModifiedIp { get; set; }
        public Nullable<decimal> Company_Id { get; set; }
        public string Action_Type { get; set; }
        public string Approval_Dept { get; set; }
    
        public virtual M_Module M_Module { get; set; }
        public virtual SectionFieldMaster SectionFieldMaster { get; set; }
        public virtual M_Company M_Company { get; set; }
        public virtual M_Plant_Group M_Plant_Group { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dept_Module_Section_Mapping
    {
        public decimal Mapping_Id { get; set; }
        public decimal Module_Id { get; set; }
        public Nullable<decimal> Plant_Group_Id { get; set; }
        public Nullable<decimal> Company_Id { get; set; }
        public decimal Department_Id { get; set; }
        public decimal Section_Id { get; set; }
        public decimal Sequence { get; set; }
        public bool Input_Rights { get; set; }
        public bool View_Rights { get; set; }
        public Nullable<bool> IsRequestor { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public string Approval_Dept { get; set; }
    
        public virtual M_Module M_Module { get; set; }
        public virtual SectionMaster SectionMaster { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldStatusMaster
    {
        public FieldStatusMaster()
        {
            this.SectionFieldMasters = new HashSet<SectionFieldMaster>();
        }
    
        public decimal ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<decimal> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<decimal> UpdatedBy { get; set; }
        public string IPAddress { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SectionFieldMaster> SectionFieldMasters { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Company
    {
        public M_Company()
        {
            this.C_Section_Feild_Mapping = new HashSet<C_Section_Feild_Mapping>();
        }
    
        public decimal Company_Id { get; set; }
        public string Company_Code { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public string CreatedIp { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public string ModifiedIp { get; set; }
        public string Company_City { get; set; }
        public Nullable<decimal> Currency_Id { get; set; }
        public Nullable<decimal> Country_Id { get; set; }
    
        public virtual ICollection<C_Section_Feild_Mapping> C_Section_Feild_Mapping { get; set; }
        public virtual M_Company M_Company1 { get; set; }
        public virtual M_Company M_Company2 { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Department
    {
        public decimal Department_Id { get; set; }
        public string Department_Name { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public string CreatedIp { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Module
    {
        public M_Module()
        {
            this.C_Section_Feild_Mapping = new HashSet<C_Section_Feild_Mapping>();
            this.Dept_Module_Section_Mapping = new HashSet<Dept_Module_Section_Mapping>();
            this.Profile_Module_Mapping = new HashSet<Profile_Module_Mapping>();
        }
    
        public decimal Module_Id { get; set; }
        public string Module_Code { get; set; }
        public string Module_Name { get; set; }
        public string Description { get; set; }
        public string Workflow_Code { get; set; }
        public string Code_Start { get; set; }
        public Nullable<decimal> Request_No_Size { get; set; }
        public bool IsActive { get; set; }
        public string ModuleType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public string CreatedIp { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public string ModifiedIp { get; set; }
    
        public virtual ICollection<C_Section_Feild_Mapping> C_Section_Feild_Mapping { get; set; }
        public virtual ICollection<Dept_Module_Section_Mapping> Dept_Module_Section_Mapping { get; set; }
        public virtual ICollection<Profile_Module_Mapping> Profile_Module_Mapping { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Plant_Group
    {
        public M_Plant_Group()
        {
            this.C_Section_Feild_Mapping = new HashSet<C_Section_Feild_Mapping>();
        }
    
        public decimal Plant_Group_Id { get; set; }
        public string Plant_Group_Code { get; set; }
        public string Plant_group_Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public string CreatedIp { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public string ModifiedIp { get; set; }
    
        public virtual ICollection<C_Section_Feild_Mapping> C_Section_Feild_Mapping { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Master
    {
        public Menu_Master()
        {
            this.Profile_Menu_Mapping = new HashSet<Profile_Menu_Mapping>();
        }
    
        public decimal Menu_ID { get; set; }
        public string Menu_Name { get; set; }
        public Nullable<decimal> Parent_Id { get; set; }
        public string Page_URL { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public string CreatedIp { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public string ModifiedIp { get; set; }
    
        public virtual ICollection<Profile_Menu_Mapping> Profile_Menu_Mapping { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Master
    {
        public Profile_Master()
        {
            this.Profile_Menu_Mapping = new HashSet<Profile_Menu_Mapping>();
            this.Profile_Module_Mapping = new HashSet<Profile_Module_Mapping>();
        }
    
        public decimal Profile_Id { get; set; }
        public string Profile_Name { get; set; }
        public bool IsActive { get; set; }
        public decimal CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<Profile_Menu_Mapping> Profile_Menu_Mapping { get; set; }
        public virtual ICollection<Profile_Module_Mapping> Profile_Module_Mapping { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Menu_Mapping
    {
        public decimal Mapping_Id { get; set; }
        public decimal Menu_ID { get; set; }
        public decimal Profile_Id { get; set; }
        public Nullable<bool> View_Right { get; set; }
        public Nullable<bool> Add_Right { get; set; }
        public Nullable<bool> Update_Right { get; set; }
        public Nullable<bool> Delete_Right { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public string CreatedIp { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public string ModifiedIp { get; set; }
        public Nullable<int> Menu_Seq { get; set; }
    
        public virtual Menu_Master Menu_Master { get; set; }
        public virtual Profile_Master Profile_Master { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Module_Mapping
    {
        public decimal Mapping_Id { get; set; }
        public decimal Profile_Id { get; set; }
        public decimal Module_Id { get; set; }
        public Nullable<bool> View_Right { get; set; }
        public Nullable<bool> Add_Right { get; set; }
        public Nullable<bool> Update_Right { get; set; }
        public Nullable<bool> Delete_Right { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public string CreatedIp { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public string ModifiedIp { get; set; }
    
        public virtual M_Module M_Module { get; set; }
        public virtual Profile_Master Profile_Master { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionFieldMaster
    {
        public SectionFieldMaster()
        {
            this.C_Section_Feild_Mapping = new HashSet<C_Section_Feild_Mapping>();
        }
    
        public decimal ID { get; set; }
        public decimal SectionID { get; set; }
        public string FieldName { get; set; }
        public string FieldDescription { get; set; }
        public Nullable<decimal> FieldStatus { get; set; }
        public string SAP_Feild { get; set; }
        public Nullable<decimal> Feild_Length { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<decimal> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<decimal> UpdatedBy { get; set; }
        public string IPAddress { get; set; }
        public string Field_Help_Text { get; set; }
        public string FeildDisplayName { get; set; }
    
        public virtual ICollection<C_Section_Feild_Mapping> C_Section_Feild_Mapping { get; set; }
        public virtual FieldStatusMaster FieldStatusMaster { get; set; }
        public virtual SectionMaster SectionMaster { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionMaster
    {
        public SectionMaster()
        {
            this.SectionFieldMasters = new HashSet<SectionFieldMaster>();
            this.Dept_Module_Section_Mapping = new HashSet<Dept_Module_Section_Mapping>();
        }
    
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Decsription { get; set; }
        public Nullable<decimal> Sequence { get; set; }
        public string Section_URL { get; set; }
        public string Module_Type { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<decimal> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<decimal> UpdatedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<SectionFieldMaster> SectionFieldMasters { get; set; }
        public virtual ICollection<Dept_Module_Section_Mapping> Dept_Module_Section_Mapping { get; set; }
    }
}
namespace DAL
{
    using System;
    
    public partial class GenerateClassPropertyC_Result
    {
        public string ProperyScript { get; set; }
    }
}
namespace DAL
{
    using System;
    
    public partial class pr_GetCompanyList_Result
    {
        public decimal Company_Id { get; set; }
        public string Company_Name { get; set; }
    }
}
