name: Push NuGet Packages to GitHub Packages

on:
  push: # Trigger manually when needed

jobs:
  push-packages:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Setup NuGet API Key
    #   run: nuget setapikey ${{ secrets.GITHUB_TOKEN }} -Source https://ghcr.io/${{ github.repository_owner }}

    - name: Push NuGet Packages
      run: |
        Write-Host "Pushing NuGet packages to GitHub Packages..."
        for /r ./packages %f in (*.nupkg) do nuget push "%f" -Source https://ghcr.io/${{ github.repository_owner }} -ApiKey "${{ secrets.PACAKEGE_TOKEN }}"
