name: Push NuGet Packages to GitHub Packages

on:
  workflow_dispatch: # Trigger manually when needed

jobs:
  push-packages:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup NuGet API Key
      run: nuget setapikey ${{ secrets.GITHUB_TOKEN }} -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    - name: Push NuGet Packages
      run: |
        Write-Host "Pushing NuGet packages to GitHub Packages..."
        nuget push ./packages/*.nupkg -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -ApiKey ${{ secrets.PACAKEGE_TOKEN }}
