name: Push NuGet Packages to GHCR

on:
  push: # Trigger on push events

jobs:
  push-packages:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Push NuGet Packages
      run: |
        Write-Host "Pushing NuGet packages to GHCR..."
        Get-ChildItem -Path ./packages -Recurse -Filter *.nupkg | ForEach-Object {
          nuget push $_.FullName -Source https://ghcr.io/${{ github.repository_owner }} -ApiKey "${{ secrets.PACAKEGE_TOKEN }}"
        }
